name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff mypy pytest

      - name: Lint
        run: ruff check .

      - name: Typecheck
        run: mypy apps

      - name: Tests
        run: pytest -q
