name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      STT_SMOKE_PLAYLIST_PATH: ${{ vars.STT_SMOKE_PLAYLIST_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify assistant static assets
        run: |
          set -euo pipefail
          assistant_dir="apps/mw/src/web/static/assistant"
          if [ ! -d "$assistant_dir" ]; then
            echo "Assistant static directory not found: $assistant_dir" >&2
            exit 1
          fi

          if [ -z "$(ls -A "$assistant_dir")" ]; then
            echo "Assistant static directory is empty: $assistant_dir" >&2
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: HTML lint (frontend/index.html)
        working-directory: frontend
        run: npx --yes htmlhint index.html

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project tooling
        run: make init

      - name: Lint
        run: make lint

      - name: Typecheck
        run: make typecheck

      - name: Tests
        run: make test

      - name: Prepare ChatKit environment
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

      - name: Start application stack
        run: make up

      - name: ChatKit smoke test
        run: ./scripts/smoke_chatkit.sh

      - name: Stop application stack
        if: always()
        run: make down

      - name: STT smoke playlist
        id: stt-smoke
        if: ${{ hashFiles('scripts/stt_smoke.py') != '' && env.OPENAI_API_KEY != '' }}
        run: |
          set -euo pipefail
          playlist_path="${STT_SMOKE_PLAYLIST_PATH:-playlists/smoke_demo}"
          if [ ! -d "$playlist_path" ]; then
            echo "Playlist directory not found: $playlist_path" >&2
            exit 1
          fi

          report_dir="reports/stt_smoke_ci"
          python scripts/stt_smoke.py --playlist "$playlist_path" --report-dir "$report_dir" --report-name "ci"

          echo "report_dir=$report_dir" >> "$GITHUB_OUTPUT"

      - name: Upload STT smoke report
        if: ${{ always() && steps.stt-smoke.outputs.report_dir != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: stt-smoke-report
          path: ${{ steps.stt-smoke.outputs.report_dir }}
          if-no-files-found: warn

  docs-quality:
    name: Docs quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install documentation tooling
        run: make init

      - name: Markdownlint
        run: make docs-markdownlint

      - name: Link checker
        run: make docs-links

      - name: Spellcheck
        run: make docs-spellcheck

      - name: Docs CI smoke test
        run: make docs-ci-smoke
