name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project tooling
        run: make init

      - name: Lint
        run: make lint

      - name: Typecheck
        run: make typecheck

      - name: Tests
        run: make test
