name: Docs CI

on:
  push:
    paths:
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/docs-ci.yml'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/docs-ci.yml'
      - 'pyproject.toml'

jobs:
  markdownlint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            README.md
            docs/**/*.md

  lychee:
    name: Link check (lychee)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --timeout 30 README.md docs/

  codespell:
    name: Spell check (codespell)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          path: |
            README.md
            docs
          skip: '*.json'
