# filename: .github/workflows/openapi-validate.yml
name: OpenAPI validation

on:
  push:
    branches: [main]
    paths:
      - "openapi.yaml"
      - ".github/workflows/openapi-validate.yml"
  pull_request:
    paths:
      - "openapi.yaml"
      - ".github/workflows/openapi-validate.yml"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install OpenAPI validator
        run: |
          python -m pip install --upgrade pip
          pip install "openapi-spec-validator[yaml]>=0.6,<0.7"

      - name: Validate specification
        run: python -m openapi_spec_validator openapi.yaml
